### ISSUE TITLE
win11 too many levels of symbolic links

### ISSUE THREAD

**Issue by seamusic** [dotnet/eShop#117]
when i run, get some error.

win11 + vs2022 17.9.0 Preview 1.1 + docker v24.0.6

![image](https://github.com/dotnet/eShop/assets/172009/30778739-d121-44ea-8248-aef69065c266)

**Comment by adityamandaleeka** [comment]
Seems like this might be a docker configuration issue in your environment. @karolz-ms Have you ever run into this before?

**Comment by karolz-ms** [comment]
Not really. Can the container be started manually via Docker CLI?

**Comment by SrushtiPasari94** [comment]
Check with @karolz-ms on teams to understand the issue in detail.

**Comment by SrushtiPasari94** [comment]
@karolz-ms 
Pinged you on MS Teams, please do reply so that we can work to resolve this issue.

**Comment by SrushtiPasari94** [comment]
As Per update from Karol, Customer is not responsive on this bug. So closing this Issue and will reopen if asked by the customer.

![image](https://github.com/dotnet/eShop/assets/136682990/228308b4-9141-4e5f-b035-d34935f0b057)
