### ISSUE TITLE
Products on catalog page get smaller when there are fewer than three shown

### ISSUE THREAD

**Issue by adityamandaleeka** [dotnet/eShop#13]
From @danroth27:

Repro steps:

- Run the web app and browse to a page with less than three products, like https://localhost:7298/?type=4&brand=1

Expected result: Products are rendered the same size as when there are three or more products
Actual result: Products are rendered smaller when there are less than three products shown

**Comment by 3lcarry** [comment]
@adityamandaleeka we can close this, it was solve as part of the responsive
