### ISSUE TITLE
Technical documentation (Onboarding)

### ISSUE THREAD

**Issue by HeyBaldur** [dotnet/eShop#133]
Hey guys, is there any technical documentation about this project? I cannot find any docs besides the image in readme.
Because I just noticed Aspire is required, not only Docker, possibly RabbitMQ, configure DB (Postgresql), Redis Image, so, there are more stuff that needs to be explained before launching for the first time the app.

**Comment by punkouter24** [comment]
same here.. Would l like someone to make a walk through on video

**Comment by HeyBaldur** [comment]
ok, it looks actually it is not big issue, however I will try to add some additional information to the setup in order to make it a bit more clear, possibly a simple onboarding doc.
