### ISSUE TITLE
ebook for eShop?

### ISSUE THREAD

**Issue by indcoder** [dotnet/eShop#137]
Previous iterations of the eShop project for the different flavours [Web, Containers etc] had an accompanying ebook that chronicled the journey in building the project; and the architectural decisions for the choices made [it also served as a list of ADRs for the project]. Will there be something similar for eShop .net 8 which is even more expansive than the previous versions.

**Comment by jamesmontemagno** [comment]
Duplicate: https://github.com/dotnet/eShop/discussions/107
