### ISSUE TITLE
Migrate BFF From Http Redirection to Yarp Api Gateway in Mobile BFF

### ISSUE THREAD

**Issue by josephaw1022** [dotnet/eShop#154]
There appears to be an inconsistency in the documentation and implementation of YARP (Yet Another Reverse Proxy) in the Mobile Backend for Frontend (BFF) example. The README's image suggests the use of YARP, but the actual implementation in the Mobile.Bff's program.cs file seems to deviate from this, particularly when compared to other examples in the Aspire project.

## README.md mobile bff icon

![image](https://github.com/dotnet/eShop/assets/47674962/095afd72-1674-4d9b-acfd-0cedd8d290ef)

## Current Mobile.Bff program.cs file 

![image](https://github.com/dotnet/eShop/assets/47674962/624bcea3-8858-46f8-a460-8ed492be2b33)

Working example of a yarp api gateway can be found here: 
https://github.com/dotnet/aspire/blob/main/samples/eShopLite/ApiGateway

**Comment by jamesmontemagno** [comment]
Will add onto backlog. Thank you for the suggestion and link the sample

**Comment by jamesmontemagno** [comment]
Implemened in: https://github.com/dotnet/eShop/pull/218
