### ISSUE TITLE
What software should I use to draw designs like this?

### ISSUE THREAD

**Issue by LuanTruongPTIT** [dotnet/eShop#158]
![Uploading eshop_architecture.png…]()

**Comment by captainsafia** [comment]
@LuanTruongPTIT Your comment didn't load fully but I assume that you are referencing the graphic that we include in our documentation. If so, we actually had a design team generate this visual from a mockup that the team provided.

@jamesmontemagno might have more insights into what tools they used.

Glad you enjoyed the visual!

**Comment by jamesmontemagno** [comment]
The architecture diagram was created in Figma by a design team working on the app with the team.
