### ISSUE TITLE
[WebToolsE2E][Aspire] When deploying eShop.web solution, running 'azd up' failed with: Property 'containers.name' has an invalid value 'EventBus'.

### ISSUE THREAD

**Issue by v-cazhang** [dotnet/eShop#176]
**REGRESSION INFO**: Not repro on Aspire 8.0.0-preview.2.23619.3

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 1 [latest build, includes Aspire 8.0.0-preview.3.24105.21 ]
3. Apply NuGet Feeds
4. Install Docker Desktop for Windows

**REPRO STEPS**
1. Clone eShop repo from preview.3 branch
2. Update NuGet.config to use the correct feeds
3. Open eShop.web.slnf
4. Build
5. Right-click solution > Open Folder in File Explorer. In the opened folder, click any place > Open in Terminal
6. Runing 'azd init', select 'Use code in the current directory' > Confirm and continue initializing my app, type a new environment name, press enter.
7. When running azd init choose to expose 'webapp' to the Internet
8. Run azd up to deploy to Azure

**ACTUAL**:
Deployment failed with error: 
ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:
![image](https://github.com/dotnet/eShop/assets/82028229/377717c5-88b4-42a1-9d08-e86ff617e97b)

Deployment Error Details:
InvalidTemplateDeployment: The template deployment 'resources' is not valid according to the validation procedure. The tracking id is 'd3323b6c-c40f-4a5a-b958-66c36f5b762b'. See inner errors for details.
ValidationForResourceFailed: Validation failed for a resource. Check 'Error.Details[0]' for more information.
ContainerAppInvalidPropertyValue: Property 'containers.name' has an invalid value 'EventBus'. A value must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character.
TraceID: 91b11fc21df8e36cdb25bb5b1b8ef017

**EXPECTED**
Deploy successfully.

**Comment by SrushtiPasari94** [comment]
@v-cazhang I am able to deploy eshop using azd.

Please follow the steps mentioned here https://github.com/dotnet/eShop?tab=readme-ov-file#use-azure-developer-cli

![image](https://github.com/dotnet/eShop/assets/136682990/9e05312e-be51-4533-86bf-8230dcaeec90)

![image](https://github.com/dotnet/eShop/assets/136682990/198bb049-6730-4965-a674-21f4420fc881)
