### ISSUE TITLE
How to connect to the Postgres instance ?

### ISSUE THREAD

**Issue by Chcoflex** [dotnet/eShop#179]
Hi,
I am using this eShop sample to assess and learn Aspire for a possible Modular Monolith type architecture.

However I can't connect to the Postgres database using pgAdmin4 using the connection strings from the configuration.

I tired localhost, 127.0.0.1 both with port 5432 using the password from the connection strings and also the password from the resource environment & I get timeout every time, as thou it's not there.

So how to workout the connection string to use from the host os? 

![image](https://github.com/dotnet/eShop/assets/140358055/818551d5-10fa-4ad2-9214-24aba4b8f1a9)

**Comment by davidfowl** [comment]
Did you look at the dashboard to see the connection information?

**Comment by Chcoflex** [comment]
Finally I found a way. :-)

![image](https://github.com/dotnet/eShop/assets/140358055/0ef3b6ab-81ee-4253-b2ea-c5a61ffa1505)

By looking up any of the dependant containers via the Dashboard, you can view the actual connection string generated. In my case it was actually using port 65500.

I can then connect using localhost with port 65500.

thanks, now for some experimenting.

**Comment by davidfowl** [comment]
We need to improve this though. Can you file an issue on the aspire repo?

**Comment by Chcoflex** [comment]
> We need to improve this though. Can you file an issue on the aspire repo?

https://github.com/dotnet/aspire/issues/2171
