### ISSUE TITLE
Wiki was not migrationed

### ISSUE THREAD

**Issue by MattMinke** [dotnet/eShop#195]
The Wiki contains a lot of useful information and helpful explanations that make this project so valuable. Can we please migrate and update the Wiki for the new repo.

Previous Wiki: https://github.com/dotnet-architecture/eShopOnContainers/wiki

**Comment by adityamandaleeka** [comment]
You're right, there was a lot of content in that wiki. Looks like there are a few main sections:

- Getting Started, which is covered in README.md in this repo. 
- "Explore" (mostly architecture notes). Much of that is out of date after the refactoring/changes that were made. We have a high level architecture diagram in the README as well, but perhaps you'd like to see more details/exposition on how everything fits together?
- Dev loop and deployment: with this new repo now based on Aspire, these things are much simpler/easier and the [Aspire docs](https://learn.microsoft.com/en-us/dotnet/aspire/get-started/aspire-overview) should cover this (beyond the getting started instructions in the README).

We'd be happy to take PRs that add useful documentation and fill in any other gaps here, but at least for now, we won't spend time on updating and migrating that wiki wholesale.
