### ISSUE TITLE
[WebToolsE2E][Aspire] Running "azd init" to initialize eShop.Web solution fails with error: "unsupported resource type: azure.openai.account.v0".

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/eShop#229]
**REGRESSION INFO:** Also repro on Aspire 8.0.0-preview.3.24105.21

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 2 [ Includes Aspire 8.0.0-preview.4.24129.7 ]
3. Apply NuGet dotnet-tools Feeds
4. Install Docker Desktop for Windows
5. Install azd [1.7.0-beta.1-daily]

**REPRO STEPS**

1. Clone eShop repo from main branch
2. Checkout the `aspire-preview.4` branch
3. Open eShop.Web.slnf ( [Bug 1985774](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/1985774) will be encountered after opening)
4. Build solution
5. Deploy using azd
    - Open the solution folder in a Command Prompt
    - Runing 'azd init', select 'Use code in the current directory' > Confirm and continue initializing my app, type a new environment name, press enter

**ACTUAL:**
ERROR: unsupported resource type: azure.openai.account.v0
![image](https://github.com/dotnet/eShop/assets/71361488/42751651-a8df-428d-aa10-7c12886a52ed)

**EXPECTED**
Running 'azd init' successfully.

**Comment by vhvb1989** [comment]
azd workaround for netAspire p4: https://github.com/Azure/azure-dev/pull/3547

**Comment by DynConcepts** [comment]
Hitting this same problem, and not understanding the "workaround" posted above... Are there explicit instructions (or even better a branch here in the Git Repository that "works"?)

**Comment by davidcorbin-atmosera** [comment]
Using https://github.com/dotnet/eShop/pull/257 with the latest Aspire helped out on this [thanks to Eric Erhardt for the pointer]

**Comment by v-sherryfan** [comment]
Unable to reproduce on 17.10 Preview 3 [Includes Aspire 8.0.0-preview.5.24201.12] using eShop `aspire-preview5` branch.

**Comment by bhogiraju** [comment]
![image](https://github.com/dotnet/eShop/assets/169258/6d41cc9f-a267-4d6e-a4db-077ffba4a2d9)
I am getting while azd init

**Comment by balachir** [comment]
@bhogiraju can you open a separate issue, please? I suspect that your issue is different than the one described in this bug. Thanks.
