### ISSUE TITLE
CS0234 Error after cloned the repo

### ISSUE THREAD

**Issue by minhthien280** [dotnet/eShop#230]
![image](https://github.com/dotnet/eShop/assets/20218327/f845438c-c7c4-4d21-b870-afc3327c8194)
I got this problem after cloned the repo down for testing.

I also got similar errors with my own project (built from the template then push to Git and have it pull down by my co-worker)

**Comment by ks1990cn** [comment]
tried creating console application? Maybe try VS reinstall or .Net version.

There is no problem which need to be reported here.

**Comment by ks1990cn** [comment]
Update VS version 17.10

**Comment by jamesmontemagno** [comment]
Please checkout https://github.com/dotnet/eShop?tab=readme-ov-file#prerequisites for requirements
