### ISSUE TITLE
run-time error

### ISSUE THREAD

**Issue by skyDuanXianBing** [dotnet/eShop#254]
PS D:\.NET\eshop\aspire\eShop> dotnet run --project src/eShop.AppHost/eShop.AppHost.csproj

Is generating...

libman.json: error LIB002: "bootstrap@5.2.3" library cannot be resolved by the "unpkg" provider [D:\.NET\eshop\aspire\eShop\src\ identit.api \Identity

.API.csproj]

libman.json: error LIB002: "jquery-validation-unobtrusive@4.0.0" library cannot be parsed by the "cdnjs" provider [D:\.NET\eshop\aspire\eShop\src\I

dentity.API\Identity.API.csproj]

libman.json: error LIB002: "jquery-validate@1.19.5" library cannot be resolved by the "cdnjs" provider [D:\.NET\eshop\aspire\eShop\src\ identit.api \I

dentity.API.csproj]

Failed to generate. Fix the build error and run again.

**Comment by skyDuanXianBing** [comment]
I fix this error ，this is chinese internet error ,  i use vpn to this error

**Comment by lhwsa2010** [comment]
I have the same error,i update the libman.json file,and fix it.
The main branch,.net9 version.
`"provider": "unpkg"`  ===>   `"provider": "jsdelivr"`
