### ISSUE TITLE
NuGet packages not consistent.

### ISSUE THREAD

**Issue by DynConcepts** [dotnet/eShop#265]
To reproduce:
1) Clear packages folder.
2) dotnet restore eShop.sln

One example of the problem is the 8.0.0, 8.0.2, 8.0.3 of microsoft.entityframeworkcore all get restored... These cause conflicts at build time....
What are not all of the Microsoft Packages properly synchronized?

**Comment by SrushtiPasari94** [comment]
@DynConcepts We are using central package management. So, we add version of every package in Directory.pakages.props. So, during build time, it takes the central package version to restore the package and not all the three version as you mentioned. Can you please pull the latest repo and try to restore the packages again.

Closing the issue. Please reopen if issue not resolved.
