### ISSUE TITLE
Mobile BFF project doesn't register health check routes

### ISSUE THREAD

**Issue by notanaverageman** [dotnet/eShop#273]
`app.MapDefaultEndpoints();` was removed in #218. Is this intentional?

**Comment by adityamandaleeka** [comment]
@Eilon @SrushtiPasari94 PTAL

**Comment by SrushtiPasari94** [comment]
@notanaverageman app.MapDefaultEndpoints(); was removed as we replaced Map forwarder with Yarp reverse Proxy for mobile BFF.

**Comment by jamesmontemagno** [comment]
I think we want to call https://github.com/dotnet/eShop/blob/main/src/eShop.ServiceDefaults/Extensions.cs#L40C43-L40C66 @adityamandaleeka ? yeah? would register both OpenTel and HealthChecks?
