### ISSUE TITLE
[WebToolsE2E][Aspire] Building the eShop solution fails with some errors: "Unable to find package xxx with version. Versions from dotnet-tools were not considered."

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/eShop#274]
**REGRESSION INFO:** Worked on Aspire 8.0.0-preview.4.24156.9

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 Preview 3 [ Includes Aspire 8.0.0-preview.5.24178.3 and SDK 8.0.300-preview.24170.4 ]
3. Install latest Aspire 8.0 P5 [8.0.0-preview.5.24179.3]
4. Apply NuGet dotnet-tools Feed
5. Install Docker Desktop for Windows

**REPRO STEPS**

1. Clone eShop repo
2. Checkout the `aspire-preview5` branch
3. Update sdk version to 8.0.300-preview.24170.4 in global.json
4. Open eShop.Web.slnf
5. Build

**ACTUAL**

![image](https://github.com/dotnet/eShop/assets/71361488/93a5fdde-201f-4b83-b889-5f5032e75e4c)

**EXPECTED**

Building the eShop.Web.slnf without any errors.

**Comment by adityamandaleeka** [comment]
@eerhardt I wasn't hitting this, can you confirm that you're not either?

**Comment by eerhardt** [comment]
> @eerhardt I wasn't hitting this, can you confirm that you're not either?

I fixed this with https://github.com/dotnet/eShop/pull/257/commits/de648e78e0fb0b86ff5bf436855f4324206f706f

**Comment by v-sherryfan** [comment]
Not reproduce on VS17.10 Preview 3 [Include 8.0.0-preview.5.24201.12].
