### ISSUE TITLE
Azure OpenAI unsupported resource type

### ISSUE THREAD

**Issue by markjbrown** [dotnet/eShop#276]
Not sure why I got this when I ran azd init. I have multiple AOAI accounts in my subscription. It blocks completion so cannot run azd up after this error.

![image](https://github.com/dotnet/eShop/assets/800166/6cb3de30-7270-4458-89cb-06cd78d82bf9)

**Comment by markjbrown** [comment]
also filed issue here, https://github.com/Azure/azure-dev/issues/3640

**Comment by aaronpowell** [comment]
dup: https://github.com/dotnet/eShop/issues/229

**Comment by adityamandaleeka** [comment]
Fixed in preview 5.
