### ISSUE TITLE
How do I enable the AI Chat?

### ISSUE THREAD

**Issue by markjbrown** [dotnet/eShop#277]
I'm trying to enable AI chat in this thing and can't seem to make this work.

I've added an endpoint and key in the appsettings for the AppHost project where it asks for one. In the WebApp project it only has "ChatModel" commented out. So tried then adding the deployment model name for GPT 3.5 16K for the account I am referencing above. Not working either.

Not sure what to try next. This says to add an API key but there is no placeholder for this.

![image](https://github.com/dotnet/eShop/assets/800166/e410c92c-ccd3-4534-b25e-ba6ef2ebab52)

**Comment by markjbrown** [comment]
Anybody else figured out how to make this work?

**Comment by markjbrown** [comment]
Anybody else having this problem? 

I'd really like to get this to work as I am using eShop to shoot a video on how to build a purchasing prediction feature using ALS that also includes doing filtering a vector search using this prediction data.

thanks.

**Comment by jamesmontemagno** [comment]
@stephentoub  are we able to add documentation for this?

**Comment by luisquintanilla** [comment]
When using Azure OpenAI, inside *eShop.AppHost/appsettings.json*, add the following section.

```
  "ConnectionStrings": {
    "OpenAi": "Endpoint=xxx;Key=xxx;"
  }
```

Replace the values with your own. 

Then, in the AppHost *Program.cs*, set this value to **true**

https://github.com/dotnet/eShop/blob/faeb3fae58d08800d0f49b04d71d18309965232c/src/eShop.AppHost/Program.cs#L73

Here's additional guidance on the Aspire OpenAI component. 

https://learn.microsoft.com/dotnet/aspire/azureai/azureai-openai-component?tabs=dotnet-cli

**Comment by markjbrown** [comment]
Thank you! @luisquintanilla and @jamesmontemagno
