### ISSUE TITLE
Azure OpenAI should use connection strings locally

### ISSUE THREAD

**Issue by aaronpowell** [dotnet/eShop#281]
_This is for Aspire Preview 5 onwards_

The method for adding Azure OpenAI Service to the AppHost, `builder.AddAzureOpenAI`, will provision a new AOAI resource if one does not already exist, which is a behaviour change between Preview 4 and Preview 5 of Aspire.

It would be better to use the `builder.AddConnectionString` for when the AppHost is running outside of a provisioning context, which would improve startup performance, and also allow people to reuse a previously deployed AOAI instance (mimicking the current behaviour).

Here's an example of how I do it in another project:

```csharp
var ai = builder.ExecutionContext.IsPublishMode ?
    builder.AddAzureOpenAI(ServiceNames.AzureOpenAI)
        .AddDeployment(new(builder.Configuration["Azure:AI:ChatDeploymentName"] ?? "gpt-4", "gpt-4", "1106"))
        .AddDeployment(new(builder.Configuration["Azure:AI:EmbeddingDeploymentName"] ?? "text-embedding-ada-002", "text-embedding-ada-002", "2")) :
    builder.AddConnectionString(ServiceNames.AzureOpenAI);
```

**Comment by davidfowl** [comment]
If the service is already deployed, the connection information is cached in user secrets. If you want to point to an already provisioned instance then you need to call AddConnectionString

**Comment by aaronpowell** [comment]
Yep, I'm just highlighting that there's going to be changing behaviour with preview5, so if we want the same workflow (ie - you don't have to add subscription + location to secrets), we should be using the `AddConnectionString` method.

**Comment by jamesmontemagno** [comment]
@aaronpowell  i think now this is resolved?

**Comment by aaronpowell** [comment]
> @aaronpowell i think now this is resolved?

Yep, there's been a change with how the AI stuff is done so it's resolved.
