### ISSUE TITLE
Use new Polly.Core APIs

### ISSUE THREAD

**Issue by martincostello** [dotnet/eShop#306]
I notice that the samples are still using the "old v7" Polly API to do retries:

https://github.com/dotnet/eShop/blob/705bb76734a32b9e7442ffe6f2041e38b8f26f12/src/EventBusRabbitMQ/RabbitMQEventBus.cs#L32-L34

Our new high-performance v8 API in Polly.Core would be better used for an example app (IMHO). Polly.Core is also AoT compatible.

Happy to do a PR if that's a welcome change.

**Comment by danmoseley** [comment]
It would be welcome, thanks @martincostello
