### ISSUE TITLE
where to find project guidance document

### ISSUE THREAD

**Issue by qinglin-yang** [dotnet/eShop#363]
i can not find any  guidance document, who can give me some introduction document about this project

**Comment by jamesmontemagno** [comment]
We are working on an eBook currently and will be out in a few months.

**Comment by YQinglin** [comment]
> We are working on an eBook currently and will be out in a few months.

What exciting news,  look forward to it.

**Comment by Houje** [comment]
Any updates on this? :D

**Comment by landonzeng** [comment]
Any updates? Very much looking forward to it, running it under Windows has been unsuccessful so far!
