### ISSUE TITLE
[WebToolsE2E][Aspire] Opening eShop.web fails with error: "Unable to find package Aspire.Azure.AI.OpenAI with version (>= 8.0.0)."

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/eShop#374]
**REGRESSION INFO:** Worked fine on main branch (Aspire 8.0 P7)

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.10 GA FB [ Includes Aspire 8.0.0 and SDK 8.0.300 ]
3. Apply NuGet darc-pub-dotnet-aspire Feed
4. Install Docker Desktop for Windows

**REPRO STEPS**

1. Clone eShop repo, checkout the `aspire-ga-version` branch
2. Open eShop.Web.slnf
3. Build 

**ACTUAL**
NU1102	Unable to find package Aspire.Azure.AI.OpenAI with version (>= 8.0.0)
 Found 1 version(s) in dotnet-tools [ Nearest version: 8.0.0-preview.8.24258.2 ]
 Versions from azure-sdk-for-net-dev were not considered
 Versions from C:\Program Files\dotnet\library-packs were not considered
  Versions from nuget were not considered
![image](https://github.com/dotnet/eShop/assets/71361488/b9b0715c-081c-46a4-8c64-b30fa87306c3)

NuGet.config
![image](https://github.com/dotnet/eShop/assets/71361488/f93de9b6-46dc-482d-bad3-39ef1941901d)

**NOTE**
- Using same machine to open eShop.Web from main branch (8.0 P7), it works fine.

**EXPECTED**
Opening eShop solution without any errors

**Comment by adityamandaleeka** [comment]
This is fixed now.
