### ISSUE TITLE
Northern Mountains company name/logos not on CELA approved fictitious companies list

### ISSUE THREAD

**Issue by CamSoper** [dotnet/eShop#376]
The Skilling org is unable to publish docs/training modules that include screenshots with the company logo visible. For example, we had to edit this screenshot to remove the logo:

![image](https://github.com/dotnet/eShop/assets/137648/76dc9856-4d9d-428a-af3b-7081bafddd92)

The workaround is easy enough from a content perspective, but we should consider rebranding this sample to be in line with CELA standards (e.g., Contoso, Fabrikam, etc.)

**Comment by jamesmontemagno** [comment]
Contoso Mountains it is!

**Comment by adityamandaleeka** [comment]
Er, AdventureWorks it is!
