### ISSUE TITLE
Add the option to use Docker Compose or Aspire

### ISSUE THREAD

**Issue by milkfrog** [dotnet/eShop#422]
Hello everyone!

Is there any chance of adding an option to use the Docker Compose instead of Aspire (maybe a different branch)? I think that having both options is a good demonstration of the differences between both Orchestration options.

Best regards,
Marcelo Contin

**Comment by jamesmontemagno** [comment]
This repo is a reference architecture for build distributed apps specifically with .NET Aspire. If you are looking for an example I would look at the previous eShopOnContainers: https://github.com/dotnet-architecture/eShopOnContainers
