### ISSUE TITLE
[WebToolsE2E][Aspire] The black area behind the shopping bag is too small, resulting in poor readability of the number of shopping bags.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/eShop#43]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.9 P1 from build [34303.117.d17.9]
3. Install latest 8.0 SDK: 8.0.100
4. Apply NuGet Feeds
5. Install Docker Desktop

**REPRO STEPS**

1. In the VS, clone the eShop repository and open eShop.Web.slnf
2. F5 / Ctrl-F5
3. Click Endpoint for 'webapp' 
4. Log in to cart and add any item to cart
5. Change the quantity to '8888' then click Update

**ACTUAL**

The black area is too small, resulting in poor readability of the number of shopping bags.
![image](https://github.com/dotnet/eShop/assets/71361488/03a4a6af-32f1-4bac-96d3-64e3838806c8)

**EXPECTED**

![image](https://github.com/dotnet/eShop/assets/71361488/64225a10-f186-4c6e-be93-72bd7ee16883)

**Comment by SrushtiPasari94** [comment]
Fixed the issue in the [PR](https://github.com/dotnet/eShop/pull/236) 
![image](https://github.com/dotnet/eShop/assets/136682990/e0a499e2-0be0-4c2b-9206-21da37384fff)

**Comment by v-sherryfan** [comment]
Verified that this issue is not reproduced on the main branch of eShop (Aspire 8.0 P3).
