### ISSUE TITLE
Serious MAUI (ClientApp) memory leak problem

### ISSUE THREAD

**Issue by DarrenStasiak** [dotnet/eShop#447]
In recent days our company discovered serious memory leak in MAUI app we are working on i.e. views set as transient don't get disposed of correctly resulting in linear memory growth. Firstly we tried using MAUI wiki page on memory leaks, which yield no concrete results to our problem. Our team decided look up how it is done in eShop demo, and we found same leak here. 

In demo we added GC.Collect, destructors to each view (on which we put a breakpoints) and label (under "Adventure Works'" title) that displays current heap size.

Examples below:
# Cheap size on startup:
![Pasted image 20240710125722](https://github.com/dotnet/eShop/assets/58084104/32525df4-38aa-4027-bb58-b7b68569bdff)

# Cheap size after opening and closing BasketView 10 times
![Pasted image 20240710125812](https://github.com/dotnet/eShop/assets/58084104/f9b56c0a-1353-4ed5-a9f9-72dc70925dde)

On opening and closing BasketView breakpoints weren't triggered single time and heap size kept increasing.

After deleting command from button in BasketView destructor started working.

![Pasted image 20240710140645](https://github.com/dotnet/eShop/assets/58084104/0e6c1d1b-2b9f-4577-8716-08a91014417e)
![Pasted image 20240710130458](https://github.com/dotnet/eShop/assets/58084104/764effef-017b-4b27-bbf6-3bfe60e8146f)

# Questions
Why does it happen, is there some explanation to why MAUI behaves this way? 
If it is not problem with MAUI, then where lays that issue?
Do we need to use some practices that aren't shown in this demo?

**Comment by jamesmontemagno** [comment]
Let me ping @jonathanpeppers to see if this with the app or is this with .NET MAUI itself somewhere

**Comment by jonathanpeppers** [comment]
@DarrenStasiak can you try the latest service release?

* https://github.com/dotnet/maui/releases/tag/8.0.70

The past few releases have fixed various memory issues. dotnet/eShop/main already has dependabot updates for this one.

The next question I have, what does `{Binding CheckoutCommand}` bind to?

It seems like the issue could be similar to:

* https://github.com/dotnet/maui/issues/16124

Do you have a custom `ICommand` where `CanExecuteChanged` is not backed by a "weak event"?

**Comment by jamesmontemagno** [comment]
I just updated the packages to 8.0.70 so should be a quick pull to test

**Comment by jamesmontemagno** [comment]
Will close out as now on newer versions and working on .NET 9
