### ISSUE TITLE
[WebToolsE2E][Aspire] Click the endpoint of the webapp in eshop dashboard and open the chatbot, the AI chat window is partially obscured.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/eShop#45]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.9 P1 from build [34303.117.d17.9]
3. Install latest 8.0 SDK: 8.0.100
4. Apply NuGet Feeds
5. Install Docker Desktop

**REPRO STEPS**

1. In the VS, clone the eShop repository and open eShop.Web.slnf
2. F5 / Ctrl-F5
3. Click Endpoint for 'webapp' and then open AI chatbot

**ACTUAL**
The AI chat window is partially obscured
![image](https://github.com/dotnet/eShop/assets/71361488/6781061e-4947-49ca-a5f7-c45438ce845c)

**EXPECTED**
![image](https://github.com/dotnet/eShop/assets/71361488/f67b9127-d988-409c-951e-759b74549b45)

**Comment by SrushtiPasari94** [comment]
Fixed in the [PR](https://github.com/dotnet/eShop/pull/236)

**Comment by v-sherryfan** [comment]
Verified that this issue is not reproduced on the main branch of eShop (Aspire 8.0 P3).
