### ISSUE TITLE
Update eshops to Aspire 8.1 candidate

### ISSUE THREAD

**Issue by danmoseley** [dotnet/eShop#458]

**Comment by joperezr** [comment]
This is in PR, Will close this once that is merged. (waiting on the packages to be in nuget.org)

**Comment by mitchdenny** [comment]
https://github.com/Azure-Samples/eShopOnAzure/pull/95

**Comment by mitchdenny** [comment]
Bringing into the 8.2 milestone so we don't forget.

**Comment by joperezr** [comment]
Is this done @mitchdenny ? Seems like so..
