### ISSUE TITLE
[WebToolsE2E] eShop.AppHost project should only contain http launch settings profile for now

### ISSUE THREAD

**Issue by balachir** [dotnet/eShop#46]
**REPRO STEPS**

1. Using VS, clone the eShop repository and open eShop.Web.slnf
2. Open eShop.AppHost > Properties > launchSettings.json

**ACTUAL**
It includes both http and https launch profiles

**EXPECTED**
It should only include the http launch profile. We don't have full support for the https profile yet.

**Comment by jamesmontemagno** [comment]
I think now we want to do the opposite per another issue, so will close this.
