### ISSUE TITLE
How to implement AppInsights into eShop in one centralized location for all the microservices?

### ISSUE THREAD

**Issue by ngaisteve1** [dotnet/eShop#465]
I want to view the Application Map for all the microservices from AppInsights. Is there a way to add AppInsight in one centralized location for all the microservices?

**Comment by adityamandaleeka** [comment]
cc @samsp-msft

**Comment by samsp-msft** [comment]
https://github.com/dotnet/eShop/pull/464

**Comment by ngaisteve1** [comment]
It works. Thanks a lot.
