### ISSUE TITLE
Update repo to .NET 9 RC 1

### ISSUE THREAD

**Issue by captainsafia** [dotnet/eShop#470]
Tracking updating to RC1 for .NET 9 when it is shipped.

**Comment by captainsafia** [comment]
When we update to .NET 9 RC 1, we should retain the version of eShop that targets .NET 8 in a seperate `release/8.0` branch. Our process for updating will be:

- Open a PR of release/9.0 against `main`.
- When the PR is ready to merge, create a branch from `main` for `release/8.0`.
- Merge the PR from the first step to main.

We'll want to follow-up and make sure that any Dependabout/branch-specific configurations are set up for both main and `release/8.0`.

For Aspire, we can assume that we can use Aspire 8 for the initial iteration of .NET 9 RC 1 support.

**Comment by adityamandaleeka** [comment]
This is done right?

**Comment by captainsafia** [comment]
Yep, we can close this out.
