### ISSUE TITLE
Can't find API Getway project

### ISSUE THREAD

**Issue by tuannh6495** [dotnet/eShop#475]
In this file: eShop\build\acr-build\queue-all.ps1
I found this line: @{ Name="eshopocelotapigw"; Image="eshop/ocelotapigw"; File="src/ApiGateways/ApiGw-Base/Dockerfile" }
But the path: "src/ApiGateways/ApiGw-Base/" dosen't exist!

**Comment by jamesmontemagno** [comment]
I think you are talking about the old eShopOnContainers: https://github.com/dotnet-architecture/eShopOnContainers/tree/dev/src


in the new eShop we use YARP for the mobile bff: https://github.com/dotnet/eShop/tree/main/src/Mobile.Bff.Shopping
