### ISSUE TITLE
Duende.IdentityServer Has a known severity vulnerability

### ISSUE THREAD

**Issue by Gjts** [dotnet/eShop#489]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误(活动)	NU1902	错误形式的警告: 包 "Duende.IdentityServer" 7.0.5 具有已知的 中 严重性漏洞，https://github.com/advisories/GHSA-ff4q-64jc-gx98	Identity.API

**Comment by frankbolero** [comment]
This is solved by PR #477
