### ISSUE TITLE
Update .NET MAUI app to use new endpoints

### ISSUE THREAD

**Issue by jamesmontemagno** [dotnet/eShop#49]
Right now the .NET MAUI app only uses fake mock data. This needs to be updated to use the new endpoints.

Working with @michaelstonis

* [ ] Update design and any performance issues
* [ ] Update to latest .NET 8 
* [ ] Use new endpoints
* [ ] Update Mobile BFF with any new apis needed
* [ ] Ability to run with or without auth

**Comment by mikekistler** [comment]
@jamesmontemagno is this done?

**Comment by michaelstonis** [comment]
@mikekistler the work here is essentially done, it just needs a few PRs to get this migrated over in order.
