### ISSUE TITLE
Availability of eShopSupport Project from Steve Sanderson's Presentation

### ISSUE THREAD

**Issue by oiBio** [dotnet/eShop#490]
Hello,

I realize this might not be the ideal place to ask, but I'm curious if there's any timeframe for when the eShopSupport project, featured in the excellent presentation by @SteveSandersonMS, will be publicly available.

The talk was a few months ago, and I'm eager to explore the project further. In the [video at ~56:20](https://youtu.be/TSNAvFJoP4M?t=3382), he shared the link: https://github.com/dotnet/eShopSupport

The project and the presentation were fantastic, and I'm eager to explore the intricacies of the solutions you came up with.

Thank you!

**Comment by SteveSandersonMS** [comment]
We've scheduled an internal review of it for early next week, and after that hope to be in a position to publish it within a further week or two (assuming no major issues are found). Hope that's OK!
