### ISSUE TITLE
Make eShopSupport public

### ISSUE THREAD

**Issue by pdevito3** [dotnet/eShop#502]
Hey y'all. Not sure if this is the best spot for it, so please close or move if needed, but I wanted to get a item up for making [the eShopSupport repo](https://github.com/dotnet/eShopSupport) from @SteveSandersonMS's [awesome talk](https://youtu.be/TSNAvFJoP4M?si=4U6WjvGpLBCtYHhC) public. 

It looked like an absolutely fantastic resource and demonstration of .NET's capabilities in a variety of domains, especially for LLM interactions (which we don't usually get good credit for) and for a more complex Aspire setup. 

I'm personally super excited to dig into it, learn a lot, and make some more resources and examples from it myself 🙂

**Comment by Allann** [comment]
Been waiting for this since watching the talk.  Really looking forward to it.

**Comment by EwoutdBoer** [comment]
Was also mentioned in this [discussion](https://github.com/dotnet/eShop/discussions/491)

**Comment by pdevito3** [comment]
Thanks for the callout! [Sounds like it's almost ready](https://github.com/dotnet/eShop/discussions/491#discussioncomment-10393985)!

**Comment by pdevito3** [comment]
it's live! https://github.com/dotnet/eShopSupport
