### ISSUE TITLE
Improve coverage for Catalog.FunctionalTests

### ISSUE THREAD

**Issue by captainsafia** [dotnet/eShop#51]
@SrushtiPasari94 Assigning this to you as the tests in Catalog.FunctionalTests are runnable now. Can you use the tests I currently added as a template to add tests for the other endpoints in the app? Let me know if you run into any issues!

**Comment by captainsafia** [comment]
@SrushtiPasari94 Any update on how this is going?

**Comment by SrushtiPasari94** [comment]
Merged the PR https://github.com/dotnet/eShop/pull/135
