### ISSUE TITLE
Add e2e tests with Playwright

### ISSUE THREAD

**Issue by jamesmontemagno** [dotnet/eShop#55]

**Comment by jamesmontemagno** [comment]
@SrushtiPasari94  let's try to add a few playwright tests that check the functionality of:

* Browsing for item
* Adding item to cart
* Removing item to cart

**Comment by SrushtiPasari94** [comment]
Added above test cases in the [PR ](https://github.com/dotnet/eShop/pull/203)

**Comment by SrushtiPasari94** [comment]
@jamesmontemagno 
Created New PR with updated test cases as per @debs-obrien suggestions.
https://github.com/dotnet/eShop/pull/235
