### ISSUE TITLE
[WebToolsE2E][Aspire] Opening eShop solution version 9.0.0 fails with error: Unable to find multiple packages for version (>= 9.0.0) even though the aspire9 feed has been added.

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/eShop#601]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.12 Preview 4 
3. Add Aspire 9 Feed
4. Install Aspire 9.0.0 ProjectTemplates
5. Install Docker Desktop for Windows

**REPRO STEPS**

1. Clone eShop repo from `main` branch [Aspire 9.0.0 rc1]
2. Manually update aspire version to 9.0.0
   - Add aspire 9.0.0 feed/mapping to nuget.config
   - Change aspire version to 9.0.0 in nuget.org
3. Open eShop.web.slnf and build

**ACTUAL**
Unable to find package Aspire.Npgsql.EntityFrameworkCore.PostgreSQL with version (>= 9.0.0)
   Found 1 version(s) in aspire9 [ Nearest version: 9.0.0-rc.2.24529.8 ]
   Versions from nuget were not considered
Unable to find package Microsoft.Extensions.Configuration.Abstractions with version (>= 9.0.0)
   Found 125 version(s) in nuget [ Nearest version: 9.0.0-rc.2.24473.5 ]
   Versions from aspire9 were not considered
Unable to find package Microsoft.Extensions.Configuration.Binder with version (>= 9.0.0)
   Found 133 version(s) in nuget [ Nearest version: 9.0.0-rc.2.24473.5 ]
   Versions from aspire9 were not considered
Unable to find package Microsoft.Extensions.Diagnostics.HealthChecks with version (>= 9.0.0)
   Found 183 version(s) in nuget [ Nearest version: 9.0.0-rc.2.24474.3 ]
   Versions from aspire9 were not considered
Unable to find package Microsoft.Extensions.Hosting with version (>= 9.0.0)
  Found 114 version(s) in nuget [ Nearest version: 9.0.0-rc.2.24473.5 ]
   Versions from aspire9 were not considered
Detected package downgrade: Grpc.Tools from 2.67.0 to centrally defined 2.66.0. Update the centrally managed package version to a higher version. 
 eShop.AppHost -> Aspire.Hosting.Azure.CognitiveServices 9.0.0 -> Grpc.Tools (>= 2.67.0) 
 eShop.AppHost -> Grpc.Tools (>= 2.66.0)
![Image](https://github.com/user-attachments/assets/e10e53ff-6916-4f78-9e54-acb8ad215ced)

**EXPECTED**

Building solution without any errors

**Comment by adityamandaleeka** [comment]
I think this is expected for now. We'll open a PR to get everything updated to GA bits once they're released later this week. cc @captainsafia

**Comment by v-sherryfan** [comment]
Closed this as not repro in main
