### ISSUE TITLE
It's not possible to run with not the .NET 8.0.100

### ISSUE THREAD

**Issue by Mishatopkek** [dotnet/eShop#92]
I installed the latest version of .net and tried to run this application, but it requires a preview version of .NET 8
To solve this, I changed global.json and chose version 8.0.100
Here's the global.json file

```json
{
  "sdk": {
    "version": "8.0.100",
    "rollForward": "latestPatch",
    "allowPrerelease": false
  }
}
```

**Comment by captainsafia** [comment]
Closed via referenced PR.
