### ISSUE TITLE
The build failed

### ISSUE THREAD

**Issue by masapasa** [dotnet/eShop#98]
dotnet run --project src/eShop.AppHost/eShop.AppHost.csproj
Building...
/.nuget/packages/grpc.tools/2.59.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB6003: The specified task executable "/.nuget/packages/grpc.tools/2.59.0/tools/macosx_x64/protoc" could not be run. System.ComponentModel.Win32Exception (13): An error occurred trying to start process '/.nuget/packages/grpc.tools/2.59.0/tools/macosx_x64/protoc' with working directory '/data/eShop/src/Basket.API'. Permission denied [/data/eShop/src/Basket.API/Basket.API.csproj]
/.nuget/packages/grpc.tools/2.59.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB6003:    at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec) [/data/eShop/src/Basket.API/Basket.API.csproj]
/.nuget/packages/grpc.tools/2.59.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB6003:    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) [/data/eShop/src/Basket.API/Basket.API.csproj]
/.nuget/packages/grpc.tools/2.59.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [/data/eShop/src/Basket.API/Basket.API.csproj]
/.nuget/packages/grpc.tools/2.59.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.Execute() [/data/eShop/src/Basket.API/Basket.API.csproj]
/.nuget/packages/grpc.tools/2.59.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB6003: The specified task executable "/.nuget/packages/grpc.tools/2.59.0/tools/macosx_x64/protoc" could not be run. System.ComponentModel.Win32Exception (13): An error occurred trying to start process '/.nuget/packages/grpc.tools/2.59.0/tools/macosx_x64/protoc' with working directory '/data/eShop/src/WebApp'. Permission denied [/data/eShop/src/WebApp/WebApp.csproj]
/.nuget/packages/grpc.tools/2.59.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB6003:    at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec) [/data/eShop/src/WebApp/WebApp.csproj]
/.nuget/packages/grpc.tools/2.59.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB6003:    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) [/data/eShop/src/WebApp/WebApp.csproj]
/.nuget/packages/grpc.tools/2.59.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [/data/eShop/src/WebApp/WebApp.csproj]
/.nuget/packages/grpc.tools/2.59.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.Execute() [/data/eShop/src/WebApp/WebApp.csproj]

The build failed. Fix the build errors and run again.

**Comment by halilkocaoz** [comment]
hey @masapasa, I look the output and there is "Permission denied", can you try it with `sudo`?

`sudo dotnet run --project src/eShop.AppHost/eShop.AppHost.csproj`

**Comment by davidfowl** [comment]
Is this error consistent?

**Comment by Gustavo-Marques19** [comment]
The same problem here. I'm using Rider on Mac. If I get the solution I'll share w/ you

**Comment by Gustavo-Marques19** [comment]
> hey @masapasa, I look the output and there is "Permission denied", can you try it with `sudo`?
> 
> `sudo dotnet run --project src/eShop.AppHost/eShop.AppHost.csproj`

worked here

**Comment by adityamandaleeka** [comment]
Glad to hear. Modifying the permissions on the files involved (with `chmod`) should resolve this sort of thing so you don't have to use sudo. I'll close this issue now since this is figured out.
